#!/usr/bin/python
# -*- coding: utf8 -*-

# telefam
# Super Simple Desktop for computer iliterated people in your family
# Author: Alfonso E.M. <alfonso@el-magnifico.org>
# License: Free (GPL3) 
# Version: 1.0 - 23/Jun/2012

from configobj import ConfigObj
import imp
import Gui
import Controls

# Load a module or plugin dinamically
def load_module(module_name, conf, interface, controller):
        fp, pathname, description = imp.find_module(module_name)
        try:
          module=imp.load_module(module_name, fp, pathname, description)
          module.main(conf, interface, controller)
        finally:
          if fp:
            fp.close()


# Main
def main():
# Load main config file
    CONF = ConfigObj("telefam.conf")

# Load module specific config files
    for module in CONF["MODULES"]["active"]:
        CONF["MODULES"][module]=ConfigObj(CONF["MODULES"]["conf_path"]+module+".conf")
     
# Create a Graphic User Interface
    interface = Gui.Interface(CONF["INTERFACE"])

# Create a Controller (keyboard, joystick..)
    controller= Controls.Control(CONF["CONTROL"])

# Main loop
    option=0
    while True:
      interface.clean()
      interface.show_main_menu(CONF["MODULES"],option)
      action=controller.wait_for_user_action()
      if action == "LEFT" and option > 0: 
        option -=1
      if action == "RIGHT" and option < len(CONF["MODULES"]["active"]) - 1: 
        option +=1
      if action == "OK": 
        module_name=CONF["MODULES"]["active"][option]
        load_module(module_name, CONF, interface, controller)

if __name__ == '__main__':
  main()
  
